### ISSUE TITLE
Missing repository xcb_cursor

### ISSUE THREAD

**Issue by qoh** [luapower/luapower-repos#1]
"xcb_cursor" is [listed as one of the repositories](https://github.com/luapower/luapower-repos/blob/master/.mgit/xcb_cursor.origin), but https://github.com/luapower/xcb_cursor does not exist. This causes `mgit clone-all` to ask for authentication and then proceed to fail:

```
Initialized empty Git repository in /home/port/.luapower/.mgit/xcb_cursor/.git/
Username for 'https://github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/luapower/xcb_cursor/' not found
rm: cannot remove ‘.mgit/xcb_cursor.exclude’: No such file or directory
ERROR: Fetch failed. Repo removed.
```

**Comment by capr** [comment]
Hi Nick,

Thanks for noticing. I removed the reference (the abandoned project is now at https://github.com/capr/xcb_cursor if anyone needs it -- there's a XCB binding there too -- I abandoned that too in favor of Xlib).
